server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: shopping_cart
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      warehouse:
        timeout-duration: 3s