server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql